# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoverBris', '0002_auto_20171001_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
