# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-08 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoverBris', '0003_auto_20171001_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
                ('photo_name', models.CharField(blank=True, max_length=256, null=True)),
                ('departments', models.CharField(blank=True, max_length=256, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
