# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoverBris', '0003_auto_20171022_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
    ]
